openapi: 3.0.0
info:
  title: demo-service API (planned additions)
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
